<?php
require __DIR__ . '/../config/config.php';
session_start(); if(empty($_SESSION['admin_id'])){header('Location: login.php');exit;}
$message='';
if(isset($_GET['delete'])){db()->prepare('DELETE FROM products WHERE id=?')->execute([(int)$_GET['delete']]);header('Location: products.php');exit;}
$editing=null;
if(isset($_GET['edit'])){$q=db()->prepare('SELECT * FROM products WHERE id=?');$q->execute([(int)$_GET['edit']]);$editing=$q->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$cat=(int)($_POST['category_id']??0);$price=(float)($_POST['price']??0);$old=$_POST['old_price']===''?null:(float)$_POST['old_price'];$stock=max(0,(int)($_POST['stock']??0));$sku=trim($_POST['sku']??'');$slug=trim($_POST['slug']??'')?:strtolower(preg_replace('/[^a-zA-Z0-9-]+/','-',trim($name)));$desc=trim($_POST['description']??'');$image=trim($_POST['image']??'');$featured=!empty($_POST['is_featured'])?1:0;$best=!empty($_POST['is_bestseller'])?1:0;$active=!empty($_POST['is_active'])?1:0;
 if($name&&$cat&&$price>=0){if($id){$q=db()->prepare('UPDATE products SET category_id=?,name=?,slug=?,description=?,image=?,price=?,old_price=?,stock=?,sku=?,is_featured=?,is_bestseller=?,is_active=? WHERE id=?');$q->execute([$cat,$name,$slug,$desc,$image,$price,$old,$stock,$sku,$featured,$best,$active,$id]);$message='প্রোডাক্ট আপডেট হয়েছে।';}else{$q=db()->prepare('INSERT INTO products(category_id,name,slug,description,image,price,old_price,stock,sku,is_featured,is_bestseller,is_active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$cat,$name,$slug,$desc,$image,$price,$old,$stock,$sku,$featured,$best,$active]);$message='প্রোডাক্ট যোগ হয়েছে।';}}else{$message='নাম, ক্যাটেগরি ও মূল্য দিন।';}}
$cats=db()->query('SELECT * FROM categories WHERE is_active=1 ORDER BY name')->fetchAll();$products=db()->query('SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id ORDER BY p.id DESC')->fetchAll();
?><!doctype html><html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Products</title><link rel="stylesheet" href="../assets/style.css"></head><body class="admin-body"><aside class="admin-sidebar"><h2>GadgetMart</h2><nav><a href="index.php">ড্যাশবোর্ড</a><a class="active" href="products.php">প্রোডাক্ট</a><a href="orders.php">অর্ডার</a><a href="settings.php">সেটিংস</a><a href="logout.php">লগআউট</a></nav></aside><main class="admin-main"><div class="topbar"><h1>প্রোডাক্ট ম্যানেজমেন্ট</h1></div><section class="panel"><h3><?= $editing?'প্রোডাক্ট সম্পাদনা':'নতুন প্রোডাক্ট'?></h3><?php if($message):?><div class="alert success"><?=e($message)?></div><?php endif;?><form method="post" class="stacked-form small-form"><input type="hidden" name="id" value="<?=e($editing['id']??0)?>"><label>নাম<input name="name" value="<?=e($editing['name']??'')?>" required></label><label>Slug<input name="slug" value="<?=e($editing['slug']??'')?>"></label><label>ক্যাটেগরি<select name="category_id" required><option value="">নির্বাচন করুন</option><?php foreach($cats as $c):?><option value="<?=e($c['id'])?>" <?=isset($editing['category_id'])&&$editing['category_id']==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></label><label>মূল্য<input type="number" step="0.01" name="price" value="<?=e($editing['price']??'')?>" required></label><label>পুরনো মূল্য<input type="number" step="0.01" name="old_price" value="<?=e($editing['old_price']??'')?>"></label><label>স্টক<input type="number" name="stock" value="<?=e($editing['stock']??0)?>" required></label><label>SKU<input name="sku" value="<?=e($editing['sku']??'')?>"></label><label>ছবি URL<input name="image" value="<?=e($editing['image']??'')?>"></label><label>বর্ণনা<textarea name="description"><?=e($editing['description']??'')?></textarea></label><div class="checkbox-row"><label><input type="checkbox" name="is_featured" <?=!empty($editing['is_featured'])?'checked':''?>> Featured</label><label><input type="checkbox" name="is_bestseller" <?=!empty($editing['is_bestseller'])?'checked':''?>> Best Seller</label><label><input type="checkbox" name="is_active" <?=!isset($editing)||!empty($editing['is_active'])?'checked':''?>> Active</label></div><button class="btn">সেভ করুন</button></form></section><section class="panel"><h3>সকল প্রোডাক্ট</h3><div class="table-wrap"><table><tr><th>নাম</th><th>ক্যাটেগরি</th><th>মূল্য</th><th>স্টক</th><th>অ্যাকশন</th></tr><?php foreach($products as $p):?><tr><td><?=e($p['name'])?></td><td><?=e($p['category_name']??'-')?></td><td>৳<?=e(number_format($p['price'],2))?></td><td><?=e($p['stock'])?></td><td><a class="btn btn-secondary" href="products.php?edit=<?=e($p['id'])?>">Edit</a> <a class="btn btn-danger" href="products.php?delete=<?=e($p['id'])?>" onclick="return confirm('Delete?')">Delete</a></td></tr><?php endforeach;?></table></div></section></main></body></html>
